In [1]:
import numpy as np
import pandas as pd

In [65]:
mtcars = pd.read_csv('C:\Dhruv\Coding\mtcars.csv')

In [14]:
mtcars.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [15]:
mtcars.shape

(32, 12)

In [5]:
#groupby

In [16]:
Model_data = mtcars.groupby('model')

In [7]:
print(Model_data)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x00000236EF36CFD0>

In [8]:
#first()

In [17]:
Model_data.first()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
model,,,,,,,,,,,
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Toyota Corona,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [10]:
#get_group

In [19]:
Model_data.get_group('Mazda RX4')

    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

In [21]:
Model_data.mpg.mean()

model
AMC Javelin            15.2
Cadillac Fleetwood     10.4
Camaro Z28             13.3
Chrysler Imperial      14.7
Datsun 710             22.8
Dodge Challenger       15.5
Duster 360             14.3
Ferrari Dino           19.7
Fiat 128               32.4
Fiat X1-9              27.3
Ford Pantera L         15.8
Honda Civic            30.4
Hornet 4 Drive         21.4
Hornet Sportabout      18.7
Lincoln Continental    10.4
Lotus Europa           30.4
Maserati Bora          15.0
Mazda RX4              21.0
Merc 230               22.8
Merc 240D              24.4
Merc 280               19.2
Merc 280C              17.8
Merc 450SE             16.4
Merc 450SL             17.3
Merc 450SLC            15.2
Pontiac Firebird       19.2
Porsche 914-2          26.0
Toyota Corona          27.7
Valiant                18.1
Volvo 142E             21.4
Name: mpg, dtype: float64

In [22]:
#No Sorting

In [25]:
mtcars.groupby('model',sort=False).first()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
model,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Toyota Corona,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [26]:
#Grouping two columns

In [27]:
mtcars.groupby(['model','mpg']).first()

                          cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
model               mpg
AMC Javelin         15.2    8  304.0  150  3.15  3.435  17.30   0   0     3
Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3
Camaro Z28          13.3    8  350.0  245  3.73  3.840  15.41   0   0     3
Chrysler Imperial   14.7    8  440.0  230  3.23  5.345  17.42   0   0     3
Datsun 710          22.8    4  108.0   93  3.85  2.320  18.61   1   1     4
Dodge Challenger    15.5    8  318.0  150  2.76  3.520  16.87   0   0     3
Duster 360          14.3    8  360.0  245  3.21  3.570  15.84   0   0     3
Ferrari Dino        19.7    6  145.0  175  3.62  2.770  15.50   0   1     5
Fiat 128            32.4    4   78.7   66  4.08  2.200  19.47   1   1     4
Fiat X1-9           27.3    4   79.0   66  4.08  1.935  18.90   1   1     4
Ford Pantera L      15.8    8  351.0  264  4.22  3.170  14.50   0   1     5
Honda Civic         30.4    4   75.7   52  4.93  1.615  18.52   1   1     4
Hornet 4 Drive      21.4    6  258.0  110  3.08  3.215  19.44   1   0     3
Hornet Sportabout   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3
Lincoln Continental 10.4    8  460.0  215  3.00  5.424  17.82   0   0     3
Lotus Europa        30.4    4   95.1  113  3.77  1.513  16.90   1   1     5
Maserati Bora       15.0    8  301.0  335  3.54  3.570  14.60   0   1     5
Mazda RX4           21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
Merc 230            22.8    4  140.8   95  3.92  3.150  22.90   1   0     4
Merc 240D           24.4    4  146.7   62  3.69  3.190  20.00   1   0     4
Merc 280            19.2    6  167.6  123  3.92  3.440  18.30   1   0     4
Merc 280C           17.8    6  167.6  123  3.92  3.440  18.90   1   0     4
Merc 450SE          16.4    8  275.8  180  3.07  4.070  17.40   0   0     3
Merc 450SL          17.3    8  275.8  180  3.07  3.730  17.60   0   0     3
Merc 450SLC         15.2    8  275.8  180  3.07  3.780  18.00   0   0     3
Pontiac Firebird    19.2    8  400.0  175  3.08  3.845  17.05   0   0     3
Porsche 914-2       26.0    4  120.3   91  4.43  2.140  16.70   0   1     5
Toyota Corona       21.5    4  120.1   97  3.70  2.465  20.01   1   0     3
                    33.9    4   71.1   65  4.22  1.835  19.90   1   1     4
Valiant             18.1    6  225.0  105  2.76  3.460  20.22   1   0     3
Volvo 142E          21.4    4  121.0  109  4.11  2.780  18.60   1   1     4

                          carb
model               mpg
AMC Javelin         15.2     2
Cadillac Fleetwood  10.4     4
Camaro Z28          13.3     4
Chrysler Imperial   14.7     4
Datsun 710          22.8     1
Dodge Challenger    15.5     2
Duster 360          14.3     4
Ferrari Dino        19.7     6
Fiat 128            32.4     1
Fiat X1-9           27.3     1
Ford Pantera L      15.8     4
Honda Civic         30.4     2
Hornet 4 Drive      21.4     1
Hornet Sportabout   18.7     2
Lincoln Continental 10.4     4
Lotus Europa        30.4     2
Maserati Bora       15.0     8
Mazda RX4           21.0     4
Merc 230            22.8     2
Merc 240D           24.4     2
Merc 280            19.2     4
Merc 280C           17.8     4
Merc 450SE          16.4     3
Merc 450SL          17.3     3
Merc 450SLC         15.2     3
Pontiac Firebird    19.2     2
Porsche 914-2       26.0     2
Toyota Corona       21.5     1
                    33.9     1
Valiant             18.1     1
Volvo 142E          21.4     2

In [30]:
#.agg

In [36]:
mtcars.groupby(['model','mpg']).agg(np.mean)

                          cyl   disp   hp  drat      wt   qsec  vs  am  gear  \
model               mpg
AMC Javelin         15.2    8  304.0  150  3.15  3.4350  17.30   0   0     3
Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.2500  17.98   0   0     3
Camaro Z28          13.3    8  350.0  245  3.73  3.8400  15.41   0   0     3
Chrysler Imperial   14.7    8  440.0  230  3.23  5.3450  17.42   0   0     3
Datsun 710          22.8    4  108.0   93  3.85  2.3200  18.61   1   1     4
Dodge Challenger    15.5    8  318.0  150  2.76  3.5200  16.87   0   0     3
Duster 360          14.3    8  360.0  245  3.21  3.5700  15.84   0   0     3
Ferrari Dino        19.7    6  145.0  175  3.62  2.7700  15.50   0   1     5
Fiat 128            32.4    4   78.7   66  4.08  2.2000  19.47   1   1     4
Fiat X1-9           27.3    4   79.0   66  4.08  1.9350  18.90   1   1     4
Ford Pantera L      15.8    8  351.0  264  4.22  3.1700  14.50   0   1     5
Honda Civic         30.4    4   75.7   52  4.93  1.6150  18.52   1   1     4
Hornet 4 Drive      21.4    6  258.0  110  3.08  3.2150  19.44   1   0     3
Hornet Sportabout   18.7    8  360.0  175  3.15  3.4400  17.02   0   0     3
Lincoln Continental 10.4    8  460.0  215  3.00  5.4240  17.82   0   0     3
Lotus Europa        30.4    4   95.1  113  3.77  1.5130  16.90   1   1     5
Maserati Bora       15.0    8  301.0  335  3.54  3.5700  14.60   0   1     5
Mazda RX4           21.0    6  160.0  110  3.90  2.7475  16.74   0   1     4
Merc 230            22.8    4  140.8   95  3.92  3.1500  22.90   1   0     4
Merc 240D           24.4    4  146.7   62  3.69  3.1900  20.00   1   0     4
Merc 280            19.2    6  167.6  123  3.92  3.4400  18.30   1   0     4
Merc 280C           17.8    6  167.6  123  3.92  3.4400  18.90   1   0     4
Merc 450SE          16.4    8  275.8  180  3.07  4.0700  17.40   0   0     3
Merc 450SL          17.3    8  275.8  180  3.07  3.7300  17.60   0   0     3
Merc 450SLC         15.2    8  275.8  180  3.07  3.7800  18.00   0   0     3
Pontiac Firebird    19.2    8  400.0  175  3.08  3.8450  17.05   0   0     3
Porsche 914-2       26.0    4  120.3   91  4.43  2.1400  16.70   0   1     5
Toyota Corona       21.5    4  120.1   97  3.70  2.4650  20.01   1   0     3
                    33.9    4   71.1   65  4.22  1.8350  19.90   1   1     4
Valiant             18.1    6  225.0  105  2.76  3.4600  20.22   1   0     3
Volvo 142E          21.4    4  121.0  109  4.11  2.7800  18.60   1   1     4

                          carb
model               mpg
AMC Javelin         15.2     2
Cadillac Fleetwood  10.4     4
Camaro Z28          13.3     4
Chrysler Imperial   14.7     4
Datsun 710          22.8     1
Dodge Challenger    15.5     2
Duster 360          14.3     4
Ferrari Dino        19.7     6
Fiat 128            32.4     1
Fiat X1-9           27.3     1
Ford Pantera L      15.8     4
Honda Civic         30.4     2
Hornet 4 Drive      21.4     1
Hornet Sportabout   18.7     2
Lincoln Continental 10.4     4
Lotus Europa        30.4     2
Maserati Bora       15.0     8
Mazda RX4           21.0     4
Merc 230            22.8     2
Merc 240D           24.4     2
Merc 280            19.2     4
Merc 280C           17.8     4
Merc 450SE          16.4     3
Merc 450SL          17.3     3
Merc 450SLC         15.2     3
Pontiac Firebird    19.2     2
Porsche 914-2       26.0     2
Toyota Corona       21.5     1
                    33.9     1
Valiant             18.1     1
Volvo 142E          21.4     2

In [38]:
#multiple operations

In [41]:
mtcars.groupby(['model','mpg']).agg([min, max])

                         cyl       disp          hp       drat           wt  \
                         min max    min    max  min  max   min   max    min
model               mpg
AMC Javelin         15.2   8   8  304.0  304.0  150  150  3.15  3.15  3.435
Cadillac Fleetwood  10.4   8   8  472.0  472.0  205  205  2.93  2.93  5.250
Camaro Z28          13.3   8   8  350.0  350.0  245  245  3.73  3.73  3.840
Chrysler Imperial   14.7   8   8  440.0  440.0  230  230  3.23  3.23  5.345
Datsun 710          22.8   4   4  108.0  108.0   93   93  3.85  3.85  2.320
Dodge Challenger    15.5   8   8  318.0  318.0  150  150  2.76  2.76  3.520
Duster 360          14.3   8   8  360.0  360.0  245  245  3.21  3.21  3.570
Ferrari Dino        19.7   6   6  145.0  145.0  175  175  3.62  3.62  2.770
Fiat 128            32.4   4   4   78.7   78.7   66   66  4.08  4.08  2.200
Fiat X1-9           27.3   4   4   79.0   79.0   66   66  4.08  4.08  1.935
Ford Pantera L      15.8   8   8  351.0  351.0  264  264  4.22  4.22  3.170
Honda Civic         30.4   4   4   75.7   75.7   52   52  4.93  4.93  1.615
Hornet 4 Drive      21.4   6   6  258.0  258.0  110  110  3.08  3.08  3.215
Hornet Sportabout   18.7   8   8  360.0  360.0  175  175  3.15  3.15  3.440
Lincoln Continental 10.4   8   8  460.0  460.0  215  215  3.00  3.00  5.424
Lotus Europa        30.4   4   4   95.1   95.1  113  113  3.77  3.77  1.513
Maserati Bora       15.0   8   8  301.0  301.0  335  335  3.54  3.54  3.570
Mazda RX4           21.0   6   6  160.0  160.0  110  110  3.90  3.90  2.620
Merc 230            22.8   4   4  140.8  140.8   95   95  3.92  3.92  3.150
Merc 240D           24.4   4   4  146.7  146.7   62   62  3.69  3.69  3.190
Merc 280            19.2   6   6  167.6  167.6  123  123  3.92  3.92  3.440
Merc 280C           17.8   6   6  167.6  167.6  123  123  3.92  3.92  3.440
Merc 450SE          16.4   8   8  275.8  275.8  180  180  3.07  3.07  4.070
Merc 450SL          17.3   8   8  275.8  275.8  180  180  3.07  3.07  3.730
Merc 450SLC         15.2   8   8  275.8  275.8  180  180  3.07  3.07  3.780
Pontiac Firebird    19.2   8   8  400.0  400.0  175  175  3.08  3.08  3.845
Porsche 914-2       26.0   4   4  120.3  120.3   91   91  4.43  4.43  2.140
Toyota Corona       21.5   4   4  120.1  120.1   97   97  3.70  3.70  2.465
                    33.9   4   4   71.1   71.1   65   65  4.22  4.22  1.835
Valiant             18.1   6   6  225.0  225.0  105  105  2.76  2.76  3.460
Volvo 142E          21.4   4   4  121.0  121.0  109  109  4.11  4.11  2.780

                                  qsec         vs      am     gear     carb  \
                            max    min    max min max min max  min max  min
model               mpg
AMC Javelin         15.2  3.435  17.30  17.30   0   0   0   0    3   3    2
Cadillac Fleetwood  10.4  5.250  17.98  17.98   0   0   0   0    3   3    4
Camaro Z28          13.3  3.840  15.41  15.41   0   0   0   0    3   3    4
Chrysler Imperial   14.7  5.345  17.42  17.42   0   0   0   0    3   3    4
Datsun 710          22.8  2.320  18.61  18.61   1   1   1   1    4   4    1
Dodge Challenger    15.5  3.520  16.87  16.87   0   0   0   0    3   3    2
Duster 360          14.3  3.570  15.84  15.84   0   0   0   0    3   3    4
Ferrari Dino        19.7  2.770  15.50  15.50   0   0   1   1    5   5    6
Fiat 128            32.4  2.200  19.47  19.47   1   1   1   1    4   4    1
Fiat X1-9           27.3  1.935  18.90  18.90   1   1   1   1    4   4    1
Ford Pantera L      15.8  3.170  14.50  14.50   0   0   1   1    5   5    4
Honda Civic         30.4  1.615  18.52  18.52   1   1   1   1    4   4    2
Hornet 4 Drive      21.4  3.215  19.44  19.44   1   1   0   0    3   3    1
Hornet Sportabout   18.7  3.440  17.02  17.02   0   0   0   0    3   3    2
Lincoln Continental 10.4  5.424  17.82  17.82   0   0   0   0    3   3    4
Lotus Europa        30.4  1.513  16.90  16.90   1   1   1   1    5   5    2
Maserati Bora       15.0  3.570  14.60  14.60   0   0   1   1    5   5    8
Mazda RX4           21.0  2.875  16.46  17.02   0   0   1   1    4   4    4
Merc 230            22.8  3.150  22.90  22.90   1   1   0   0    4   4    2
Merc 240D           24.4  3.190  20.00  20.00   1   1   0   0    4   4    2
Merc 280            19.2  3.440  18.30  18.30   1   1   0   0    4   4    4
Merc 280C           17.8  3.440  18.90  18.90   1   1   0   0    4   4    4
Merc 450SE          16.4  4.070  17.40  17.40   0   0   0   0    3   3    3
Merc 450SL          17.3  3.730  17.60  17.60   0   0   0   0    3   3    3
Merc 450SLC         15.2  3.780  18.00  18.00   0   0   0   0    3   3    3
Pontiac Firebird    19.2  3.845  17.05  17.05   0   0   0   0    3   3    2
Porsche 914-2       26.0  2.140  16.70  16.70   0   0   1   1    5   5    2
Toyota Corona       21.5  2.465  20.01  20.01   1   1   0   0    3   3    1
                    33.9  1.835  19.90  19.90   1   1   1   1    4   4    1
Valiant             18.1  3.460  20.22  20.22   1   1   0   0    3   3    1
Volvo 142E          21.4  2.780  18.60  18.60   1   1   1   1    4   4    2


                         max
model               mpg
AMC Javelin         15.2   2
Cadillac Fleetwood  10.4   4
Camaro Z28          13.3   4
Chrysler Imperial   14.7   4
Datsun 710          22.8   1
Dodge Challenger    15.5   2
Duster 360          14.3   4
Ferrari Dino        19.7   6
Fiat 128            32.4   1
Fiat X1-9           27.3   1
Ford Pantera L      15.8   4
Honda Civic         30.4   2
Hornet 4 Drive      21.4   1
Hornet Sportabout   18.7   2
Lincoln Continental 10.4   4
Lotus Europa        30.4   2
Maserati Bora       15.0   8
Mazda RX4           21.0   4
Merc 230            22.8   2
Merc 240D           24.4   2
Merc 280            19.2   4
Merc 280C           17.8   4
Merc 450SE          16.4   3
Merc 450SL          17.3   3
Merc 450SLC         15.2   3
Pontiac Firebird    19.2   2
Porsche 914-2       26.0   2
Toyota Corona       21.5   1
                    33.9   1
Valiant             18.1   1
Volvo 142E          21.4   2

In [42]:
#.agg on multiple columns

In [48]:
mtcars.groupby(
    ['model','mpg']
).agg(
    {
        'mpg': [min, max],
        'carb': "count",
        'gear': [min, max]
    }
)

                           mpg        carb gear
                           min   max count  min max
model               mpg
AMC Javelin         15.2  15.2  15.2     1    3   3
Cadillac Fleetwood  10.4  10.4  10.4     1    3   3
Camaro Z28          13.3  13.3  13.3     1    3   3
Chrysler Imperial   14.7  14.7  14.7     1    3   3
Datsun 710          22.8  22.8  22.8     1    4   4
Dodge Challenger    15.5  15.5  15.5     1    3   3
Duster 360          14.3  14.3  14.3     1    3   3
Ferrari Dino        19.7  19.7  19.7     1    5   5
Fiat 128            32.4  32.4  32.4     1    4   4
Fiat X1-9           27.3  27.3  27.3     1    4   4
Ford Pantera L      15.8  15.8  15.8     1    5   5
Honda Civic         30.4  30.4  30.4     1    4   4
Hornet 4 Drive      21.4  21.4  21.4     1    3   3
Hornet Sportabout   18.7  18.7  18.7     1    3   3
Lincoln Continental 10.4  10.4  10.4     1    3   3
Lotus Europa        30.4  30.4  30.4     1    5   5
Maserati Bora       15.0  15.0  15.0     1    5   5
Mazda RX4           21.0  21.0  21.0     2    4   4
Merc 230            22.8  22.8  22.8     1    4   4
Merc 240D           24.4  24.4  24.4     1    4   4
Merc 280            19.2  19.2  19.2     1    4   4
Merc 280C           17.8  17.8  17.8     1    4   4
Merc 450SE          16.4  16.4  16.4     1    3   3
Merc 450SL          17.3  17.3  17.3     1    3   3
Merc 450SLC         15.2  15.2  15.2     1    3   3
Pontiac Firebird    19.2  19.2  19.2     1    3   3
Porsche 914-2       26.0  26.0  26.0     1    5   5
Toyota Corona       21.5  21.5  21.5     1    3   3
                    33.9  33.9  33.9     1    4   4
Valiant             18.1  18.1  18.1     1    3   3
Volvo 142E          21.4  21.4  21.4     1    4   4

In [49]:
#.apply()

In [69]:
mtcars.groupby('model').apply(lambda grp: grp.count())

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
model,,,,,,,,,,,,
AMC Javelin,1,1,1,1,1,1,1,1,1,1,1,1
Cadillac Fleetwood,1,1,1,1,1,1,1,1,1,1,1,1
Camaro Z28,1,1,1,1,1,1,1,1,1,1,1,1
Chrysler Imperial,1,1,1,1,1,1,1,1,1,1,1,1
Datsun 710,1,1,1,1,1,1,1,1,1,1,1,1
Dodge Challenger,1,1,1,1,1,1,1,1,1,1,1,1
Duster 360,1,1,1,1,1,1,1,1,1,1,1,1
Ferrari Dino,1,1,1,1,1,1,1,1,1,1,1,1
Fiat 128,1,1,1,1,1,1,1,1,1,1,1,1
Fiat X1-9,1,1,1,1,1,1,1,1,1,1,1,1
Ford Pantera L,1,1,1,1,1,1,1,1,1,1,1,1
Honda Civic,1,1,1,1,1,1,1,1,1,1,1,1
Hornet 4 Drive,1,1,1,1,1,1,1,1,1,1,1,1
Hornet Sportabout,1,1,1,1,1,1,1,1,1,1,1,1
Lincoln Continental,1,1,1,1,1,1,1,1,1,1,1,1
Lotus Europa,1,1,1,1,1,1,1,1,1,1,1,1
Maserati Bora,1,1,1,1,1,1,1,1,1,1,1,1
Mazda RX4,2,2,2,2,2,2,2,2,2,2,2,2
Merc 230,1,1,1,1,1,1,1,1,1,1,1,1
Merc 240D,1,1,1,1,1,1,1,1,1,1,1,1
Merc 280,1,1,1,1,1,1,1,1,1,1,1,1
Merc 280C,1,1,1,1,1,1,1,1,1,1,1,1
Merc 450SE,1,1,1,1,1,1,1,1,1,1,1,1
Merc 450SL,1,1,1,1,1,1,1,1,1,1,1,1
Merc 450SLC,1,1,1,1,1,1,1,1,1,1,1,1
Pontiac Firebird,1,1,1,1,1,1,1,1,1,1,1,1
Porsche 914-2,1,1,1,1,1,1,1,1,1,1,1,1
Toyota Corona,2,2,2,2,2,2,2,2,2,2,2,2
Valiant,1,1,1,1,1,1,1,1,1,1,1,1
Volvo 142E,1,1,1,1,1,1,1,1,1,1,1,1

In [71]:
#Transform

In [73]:
mtcars["trans"] = mtcars.groupby('model')["mpg"].transform('mean')

In [74]:
mtcars

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,trans
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,21.0
1,Mazda RX4,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,21.0
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,22.8
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,21.4
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,18.7
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,18.1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,14.3
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,24.4
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,22.8
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,19.2
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,17.8
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,16.4
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,17.3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,15.2
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,10.4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,10.4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,14.7
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,32.4
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,30.4
19,Toyota Corona,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,27.7
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,27.7
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,15.5
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,15.2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,13.3
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,19.2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,27.3
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,26.0
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,30.4
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,15.8
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,19.7
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,15.0
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,21.4